### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by osbym**
Revised README file. I touched it up a little. Let me know if we need to add anything else.

### CODE REVIEW

**Comment by osbym** [comment]
I was updating the README as well, but I see Eduardo knocked it out.

**Comment by osbym** [comment]
Updated README with deployed link.

**Review by osbym — COMMENTED** [review]
Updated README!

**Review by HacAtac — APPROVED** [review]
Awesome, thanks Marcus you're the man!

**Pull request merged**
